global:
  nodeSelector:
    workload: application
    kubernetes.io/arch: arm64
  tolerations:
    - key: workload
      value: application
      effect: NoSchedule

configs:
  rbac:
    scopes: "[groups, email]"
