# Helm chart values
grafana:
  persistence:
    enabled: true
    size: 10Gi
    inMemory:
      enabled: false
 storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: gp2
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi