volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: lua-script
    configMap:
      name: fluent-bit-lua-script

volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: lua-script
    mountPath: /fluent-bit/etc/scripts 

additionalFilters: |
  [FILTER]
      Name    lua
      Match   *
      Script  /fluent-bit/etc/scripts/filter.lua
      Call    filter_record