filter:
  enabled: true
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "off"
  mergeLogKey: "data"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "On"
  bufferSize: "32k"
# additionalFilters: |
#   [FILTER]
#       Name stdout
#       Match *
# # # [FILTER]
# # #     Name            nest
# # #     Match           kube.*
# # #     Operation       lift
# # #     Nested_under    kubernetes
# # #     Add_prefix      kubernetes.