filter:
  enabled: true
  match: "kube.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "off"
  mergeLogKey: "data"
  keepLog: "on"
  k8sLoggingParser: "on"
  k8sLoggingExclude: "on"
  bufferSize: "32k"
# filter:
#   extraFilters: |
#     Annotations     off
    
volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: lua-script
    configMap:
      name: fluent-bit-lua-script

volumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: lua-script
    mountPath: /fluent-bit/etc/scripts 
# volumes:
# - name: lua-script
#   configMap:
#     name: fluent-bit-lua-script

# volumeMounts:
# - name: lua-script
#   mountPath: /fluent-bit/etc/scripts 
additionalFilters: |
  [FILTER]
      Name    lua
      Match   kube.*
      Script  /fluent-bit/etc/scripts/filter.lua
      Call    filter_record
# # # [FILTER]
# # #     Name            nest
# # #     Match           kube.*
# # #     Operation       lift
# # #     Nested_under    kubernetes
# # #     Add_prefix      kubernetes.